name: "Build & Release"
on:
  push:
    branches:
      - main
jobs:   
  build:
    name: Build & Release  
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    steps:
        #1 Checkout repository
        - name: Checkout Repository
          uses: actions/checkout@v3
          
        #2 Setup Java
        - name: Set Up Java
          uses: actions/setup-java@v3.12.0
          with:
            distribution: 'oracle'
            java-version: '17'
        
        #3 Setup Flutter
        - name: Set Up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.19.0'
            channel: 'stable' 

        #4 Install Dependencies
        - name: Install Dependencies
          run: flutter pub get

        #5 Build apk
        - name: Build APK
          run: flutter build apk --release

        #6 Get those build to be available to download
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: Releases
            path: |
              build/app/outputs/flutter-apk/app-release.apk
    
        #7 Create release with those builds
        - name: Create Release
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/flutter-apk/app-release.apk"
            tag: v1.0.${{ github.run_number }}
            